local altSkins = {}

altSkins.origPlayerSprites = {
  {'WitchOrig/walk_left', 4, padding = 2, width = 16, height = 16},
  {'WitchOrig/walk_up', 4, padding = 2, width = 16, height = 16},
  {'WitchOrig/walk_down', 4, padding = 2, width = 16, height = 16},
  {'WitchOrig/push_up', 4, padding = 2, width = 16, height = 16},
  {'WitchOrig/push_left', 4, padding = 2, width = 16, height = 16},
  {'WitchOrig/push_down', 2, padding = 2, width = 16, height = 16},
  {'WitchOrig/grip_up', 4, padding = 2, width = 16, height = 16},
  {'WitchOrig/grip_left', 4, padding = 2, width = 16, height = 16},
  {'WitchOrig/grip_down', 2, padding = 2, width = 16, height = 16},
  {'WitchOrig/lifting_up', 1, padding = 2, width = 16, height = 16},
  {'WitchOrig/lifting_left', 1, padding = 2, width = 16, height = 16},
  {'WitchOrig/lifting_down', 1, padding = 2, width = 16, height = 16},
  {'WitchOrig/lifted_up', 4, padding = 2, width = 16, height = 16},
  {'WitchOrig/lifted_left', 4, padding = 2, width = 16, height = 16},
  {'WitchOrig/lifted_down', 4, padding = 2, width = 16, height = 16},
  {'WitchOrig/halt_up', 1, padding = 2, width = 16, height = 16},
  {'WitchOrig/halt_left', 1, padding = 2, width = 16, height = 16},
  {'WitchOrig/halt_down', 1, padding = 2, width = 16, height = 16},
  {'WitchOrig/hurt_up', 1, padding = 2, width = 16, height = 16},
  {'WitchOrig/hurt_left', 1, padding = 2, width = 16, height = 16},
  {'WitchOrig/hurt_down', 1, padding = 2, width = 16, height = 16},
  {'WitchOrig/still_up', 1, padding = 2, width = 16, height = 16},
  {'WitchOrig/still_left', 1, padding = 2, width = 16, height = 16},
  {'WitchOrig/still_down', 1, padding = 2, width = 16, height = 16},
  {'WitchOrig/swing_up', 2, padding = 2, width = 16, height = 16},
  {'WitchOrig/swing_left', 2, padding = 2, width = 16, height = 16},
  {'WitchOrig/swing_down', 2, padding = 2, width = 16, height = 16},
  {'WitchOrig/hold_up', 4, padding = 2, width = 16, height = 16},
  {'WitchOrig/hold_left', 4, padding = 2, width = 16, height = 16},
  {'WitchOrig/hold_down', 4, padding = 2, width = 16, height = 16},
  {'WitchOrig/shoot_up', 4, padding = 2, width = 16, height = 16},
  {'WitchOrig/shoot_left', 4, padding = 2, width = 16, height = 16},
  {'WitchOrig/shoot_down', 4, padding = 2, width = 16, height = 16},
  {'WitchOrig/jump_down', 3, padding = 2, width = 16, height = 16},
  {'WitchOrig/jump_left', 3, padding = 2, width = 16, height = 16},
  {'WitchOrig/jump_up', 3, padding = 2, width = 16, height = 16},
  {'WitchOrig/mark_down', 1, padding = 2, width = 16, height = 16},
  {'WitchOrig/recall_down', 1, padding = 2, width = 16, height = 16},
  {'WitchOrig/display_down', 2, padding = 2, width = 16, height = 16},
  {'WitchOrig/drown_down', 2, padding = 2, width = 16, height = 16},
  {'WitchOrig/climb_up', 2, padding = 2, width = 16, height = 16},
  {'WitchOrig/plummet', 3, padding = 2, width = 16, height = 16},
  {'WitchOrig/die', 7, padding = 2, width = 16, height = 16},
  {'WitchOrig/shadow', 1, padding = 2, width = 16, height = 16},
  {'WitchOrig/defaultGrass', 2, padding = 2, width = 16, height = 16},
  {'WitchOrig/defaultWaterRipples', 4, padding = 2, width = 16, height = 6},
  {'health', 5, padding = 2, width = 7, height = 7},
  {'rupees', 1, padding = 0, width = 7, height = 7},
  {'Test', 1, padding = 0},
}

return altSkins
