local altSkins = {}

altSkins.origPlayerSprites = {
  {'WitchOrig/walk_left', 4, padding = 2, width = 16, height = 16},
  {'WitchOrig/walk_up', 4, padding = 2, width = 16, height = 16},
  {'WitchOrig/walk_down', 4, padding = 2, width = 16, height = 16},
  {'WitchOrig/push_up', 4, padding = 2, width = 16, height = 16},
  {'WitchOrig/push_left', 4, padding = 2, width = 16, height = 16},
  {'WitchOrig/push_down', 2, padding = 2, width = 16, height = 16},
  {'WitchOrig/grip_up', 4, padding = 2, width = 16, height = 16},
  {'WitchOrig/grip_left', 4, padding = 2, width = 16, height = 16},
  {'WitchOrig/grip_down', 2, padding = 2, width = 16, height = 16},
  {'WitchOrig/lifting_up', 1, padding = 2, width = 16, height = 16},
  {'WitchOrig/lifting_left', 1, padding = 2, width = 16, height = 16},
  {'WitchOrig/lifting_down', 1, padding = 2, width = 16, height = 16},
  {'WitchOrig/lifted_up', 4, padding = 2, width = 16, height = 16},
  {'WitchOrig/lifted_left', 4, padding = 2, width = 16, height = 16},
  {'WitchOrig/lifted_down', 4, padding = 2, width = 16, height = 16},
  {'WitchOrig/halt_up', 1, padding = 2, width = 16, height = 16},
  {'WitchOrig/halt_left', 1, padding = 2, width = 16, height = 16},
  {'WitchOrig/halt_down', 1, padding = 2, width = 16, height = 16},
  {'WitchOrig/hurt_up', 1, padding = 2, width = 16, height = 16},
  {'WitchOrig/hurt_left', 1, padding = 2, width = 16, height = 16},
  {'WitchOrig/hurt_down', 1, padding = 2, width = 16, height = 16},
  {'WitchOrig/still_up', 1, padding = 2, width = 16, height = 16},
  {'WitchOrig/still_left', 1, padding = 2, width = 16, height = 16},
  {'WitchOrig/still_down', 1, padding = 2, width = 16, height = 16},
  {'WitchOrig/cape_up', 1, padding = 2, width = 16, height = 16},
  {'WitchOrig/cape_left', 1, padding = 2, width = 16, height = 16},
  {'WitchOrig/cape_down', 1, padding = 2, width = 16, height = 16},
  {'WitchOrig/swing_up', 2, padding = 2, width = 16, height = 16},
  {'WitchOrig/swing_left', 2, padding = 2, width = 16, height = 16},
  {'WitchOrig/swing_down', 2, padding = 2, width = 16, height = 16},
  {'WitchOrig/hold_up', 4, padding = 2, width = 16, height = 16},
  {'WitchOrig/hold_left', 4, padding = 2, width = 16, height = 16},
  {'WitchOrig/hold_down', 4, padding = 2, width = 16, height = 16},
  {'WitchOrig/shoot_up', 4, padding = 2, width = 16, height = 16},
  {'WitchOrig/shoot_left', 4, padding = 2, width = 16, height = 16},
  {'WitchOrig/shoot_down', 4, padding = 2, width = 16, height = 16},
  {'WitchOrig/jump_down', 3, padding = 2, width = 16, height = 16},
  {'WitchOrig/jump_left', 3, padding = 2, width = 16, height = 16},
  {'WitchOrig/jump_up', 3, padding = 2, width = 16, height = 16},
  {'WitchOrig/roll_down', 4, padding = 2, width = 16, height = 16},
  {'WitchOrig/roll_left', 4, padding = 2, width = 16, height = 16},
  {'WitchOrig/roll_up', 4, padding = 2, width = 16, height = 16},
  {'WitchOrig/mdust_down', 2, padding = 2, width = 16, height = 16},
  {'WitchOrig/mdust_left', 2, padding = 2, width = 16, height = 16},
  {'WitchOrig/mdust_up', 2, padding = 2, width = 16, height = 16},
  {'WitchOrig/mark_down', 1, padding = 2, width = 16, height = 16},
  {'WitchOrig/recall_down', 1, padding = 2, width = 16, height = 16},
  {'WitchOrig/display_down', 2, padding = 2, width = 16, height = 16},
  {'WitchOrig/eating_down', 2, padding = 2, width = 16, height = 16},
  {'WitchOrig/sleeping_down', 2, padding = 2, width = 16, height = 16},
  {'WitchOrig/harp_down', 2, padding = 2, width = 20, height = 16},
  {'WitchOrig/drown_down', 2, padding = 2, width = 16, height = 16},
  {'WitchOrig/climb_up', 2, padding = 2, width = 16, height = 16},
  {'WitchOrig/plummet', 3, padding = 2, width = 16, height = 16},
  {'WitchOrig/die', 7, padding = 2, width = 16, height = 16},
  {'WitchOrig/shadow', 1, padding = 2, width = 16, height = 16},
  {'WitchOrig/defaultGrass', 2, padding = 2, width = 16, height = 16},
  {'WitchOrig/defaultWaterRipples', 4, padding = 2, width = 16, height = 6}
}

altSkins.zeldaPlayerSprites = {
  {'Zelda/walk_left', 2, padding = 2, width = 16, height = 18},
  {'Zelda/walk_up', 2, padding = 2, width = 16, height = 18},
  {'Zelda/walk_down', 2, padding = 2, width = 16, height = 18},
  {'Zelda/push_up', 2, padding = 2, width = 16, height = 18},
  {'Zelda/push_left', 2, padding = 2, width = 16, height = 18},
  {'Zelda/push_down', 2, padding = 2, width = 16, height = 16},
  {'Zelda/grip_up', 2, padding = 2, width = 16, height = 18},
  {'Zelda/grip_left', 4, padding = 2, width = 16, height = 18},
  {'Zelda/grip_down', 2, padding = 2, width = 16, height = 18},
  {'Zelda/lifting_up', 1, padding = 2, width = 16, height = 18},
  {'Zelda/lifting_left', 1, padding = 2, width = 16, height = 18},
  {'Zelda/lifting_down', 1, padding = 2, width = 16, height = 18},
  {'Zelda/lifted_up', 4, padding = 2, width = 16, height = 18},
  {'Zelda/lifted_left', 4, padding = 2, width = 16, height = 18},
  {'Zelda/lifted_down', 4, padding = 2, width = 16, height = 18},
  {'Zelda/halt_up', 1, padding = 2, width = 16, height = 18}, -- its 19 but looks better 18
  {'Zelda/halt_left', 1, padding = 2, width = 16, height = 18}, -- its 19 but looks better 18
  {'Zelda/halt_down', 1, padding = 2, width = 16, height = 18}, -- its 19 but looks better 18
  {'Zelda/hurt_up', 1, padding = 2, width = 16, height = 18}, -- its 19 but looks better 18
  {'Zelda/hurt_left', 1, padding = 2, width = 16, height = 18}, -- its 19 but looks better 18
  {'Zelda/hurt_down', 1, padding = 2, width = 16, height = 18}, -- its 19 but looks better 18
  {'Zelda/still_up', 1, padding = 2, width = 16, height = 18},
  {'Zelda/still_left', 1, padding = 2, width = 16, height = 18},
  {'Zelda/still_down', 1, padding = 2, width = 16, height = 18},
  {'Zelda/cape_up', 1, padding = 2, width = 16, height = 16},
  {'Zelda/cape_left', 1, padding = 2, width = 16, height = 16},
  {'Zelda/cape_down', 1, padding = 2, width = 16, height = 16},
  {'Zelda/swing_up', 2, padding = 2, width = 16, height = 18},
  {'Zelda/swing_left', 2, padding = 2, width = 16, height = 18},
  {'Zelda/swing_down', 2, padding = 2, width = 16, height = 18},
  {'Zelda/hold_up', 2, padding = 2, width = 16, height = 18},
  {'Zelda/hold_left', 2, padding = 2, width = 16, height = 18},
  {'Zelda/hold_down', 2, padding = 2, width = 16, height = 18},
  {'Zelda/shoot_up', 2, padding = 2, width = 16, height = 18},
  {'Zelda/shoot_left', 2, padding = 2, width = 16, height = 18},
  {'Zelda/shoot_down', 2, padding = 2, width = 16, height = 18},
  {'Zelda/jump_down', 4, padding = 2, width = 16, height = 18},
  {'Zelda/jump_left', 4, padding = 2, width = 16, height = 18},
  {'Zelda/jump_up', 4, padding = 2, width = 16, height = 18},
  {'Zelda/roll_down', 4, padding = 2, width = 16, height = 16},
  {'Zelda/roll_left', 4, padding = 2, width = 16, height = 16},
  {'Zelda/roll_up', 4, padding = 2, width = 16, height = 16},
  {'Zelda/mdust_down', 2, padding = 2, width = 16, height = 16},
  {'Zelda/mdust_left', 2, padding = 2, width = 16, height = 16},
  {'Zelda/mdust_up', 2, padding = 2, width = 16, height = 16},
  {'Zelda/mark_down', 1, padding = 2, width = 16, height = 18},
  {'Zelda/recall_down', 1, padding = 2, width = 16, height = 18},
  {'Zelda/display_down', 2, padding = 2, width = 16, height = 18},
  {'Zelda/eating_down', 2, padding = 2, width = 16, height = 16},
  {'Zelda/sleeping_down', 2, padding = 2, width = 16, height = 16},
  {'Zelda/harp_down', 2, padding = 2, width = 20, height = 16},
  {'Zelda/drown_down', 2, padding = 2, width = 16, height = 16},
  {'Zelda/climb_up', 2, padding = 2, width = 16, height = 18},
  {'Zelda/plummet', 3, padding = 2, width = 16, height = 18},
  {'Zelda/die', 7, padding = 2, width = 18, height = 19},
  {'Zelda/shadow', 1, padding = 2, width = 16, height = 18},
  {'Zelda/defaultGrass', 2, padding = 2, width = 16, height = 18},
  {'Zelda/defaultWaterRipples', 4, padding = 2, width = 16, height = 6}
}

return altSkins
